nc: 12
names: ['black-bishop',
 'black-king', 
 'black-knight', 
 'black-pawn', 
 'black-queen', 
 'black-rook', 
 'white-bishop', 
 'white-king', 
 'white-knight', 
 'white-pawn', 
 'white-queen', 
 'white-rook']
path: /root/Chess-vision-Deep-Learning-Final-Project-master/datasets/pieces_detection
train: /root/Chess-vision-Deep-Learning-Final-Project-master/datasets/pieces_detection/train/images
val: /root/Chess-vision-Deep-Learning-Final-Project-master/datasets/pieces_detection/valid/images
test: /root/Chess-vision-Deep-Learning-Final-Project-master/datasets/pieces_detection/test/images
val: valid






